<a href="https://colab.research.google.com/github/zuozuo11/UMASS/blob/main/mult_reg_and_correlation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [6]:
data = pd.read_csv('/content/for_mult_reg.csv',encoding='latin1')

In [7]:
data

,Unnamed: 0,crsp_portno,m_date,fund_name,weight_mret,mgr_name,mktrf,smb,hml,rf,umd,efr
0,0,1000005,2005/1/1,BlackRock Natural Resources Trust; Investor A ...,0.028175,Robert M. Shearer,0.0343,-0.0003,-0.0022,0.0016,-0.0287,0.026575
1,1,1000009,2005/1/1,Merrill Lynch Equity Dividend Fund; Class A Sh...,-0.005693,Robert M. Shearer,0.0343,-0.0003,-0.0022,0.0016,-0.0287,-0.007293
2,2,1000017,2005/1/1,"Jennison Small Company Fund, Inc; Class A Shares",-0.017783,John P. Mullman,0.0343,-0.0003,-0.0022,0.0016,-0.0287,-0.019383
3,3,1000030,2005/1/1,"AllianceBernstein Growth & Income Fund, Inc; C...",-0.008071,Frank Caruso,0.0343,-0.0003,-0.0022,0.0016,-0.0287,-0.009671
4,4,1000054,2005/1/1,Fidelity Advisor Series I: Fidelity Advisor Eq...,-0.032812,Jason Weiner,0.0343,-0.0003,-0.0022,0.0016,-0.0287,-0.034412
...,...,...,...,...,...,...,...,...,...,...,...,...
71318,71318,1052687,2021/12/1,ALPS ETF Trust: ALPS Hillman Active Value ETF,0.045427,Mark A. Hillman,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.045427
71319,71319,1052803,2021/12/1,Ultimus Managers Trust: Westwood SmallCap Grow...,0.032446,Adrian Helfert,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.032446
71320,71320,1052862,2021/12/1,"Morgan Stanley Institutional Fund, Inc: US Foc...",0.096784,Laurel Durkay,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.096784
71321,71321,1052900,2021/12/1,Collaborative Investment Series Trust: Tuttle ...,0.073453,Matthew Tuttle,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.073453
71322,71322,1052938,2021/12/1,Vanguard Whitehall Funds: Vanguard Advice Sele...,0.082951,Donald J. Kilbride,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.082951

In [8]:
feature_cols = ['mktrf','hml','smb','umd']

In [9]:
X = data[feature_cols]# Feature
y = data.efr #target variable

In [11]:
reg = sm.OLS(y, X).fit()
reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                    efr   R-squared (uncentered):                   0.016
Model:                            OLS   Adj. R-squared (uncentered):              0.016
Method:                 Least Squares   F-statistic:                              296.0
Date:                Mon, 30 Jan 2023   Prob (F-statistic):                   5.91e-253
Time:                        14:40:33   Log-Likelihood:                          84311.
No. Observations:               71323   AIC:                                 -1.686e+05
Df Residuals:                   71319   BIC:                                 -1.686e+05
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
mktrf          0.1669      0.007     23.856      0.000       0.153       0.181
hml           -0.1093      0.011    -10.252      0.000      -0.130      -0.088
smb           -0.1815      0.013    -14.348      0.000      -0.206      -0.157
umd           -0.1113      0.007    -16.043      0.000      -0.125      -0.098
==============================================================================
Omnibus:                   182253.904   Durbin-Watson:                   1.332
Prob(Omnibus):                  0.000   Jarque-Bera (JB):      36390117380.664
Skew:                          27.815   Prob(JB):                         0.00
Kurtosis:                    3501.869   Cond. No.                         2.68
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [13]:
data['res']=pd.DataFrame(reg.resid)

In [14]:
data

,Unnamed: 0,crsp_portno,m_date,fund_name,weight_mret,mgr_name,mktrf,smb,hml,rf,umd,efr,res
0,0,1000005,2005/1/1,BlackRock Natural Resources Trust; Investor A ...,0.028175,Robert M. Shearer,0.0343,-0.0003,-0.0022,0.0016,-0.0287,0.026575,0.017361
1,1,1000009,2005/1/1,Merrill Lynch Equity Dividend Fund; Class A Sh...,-0.005693,Robert M. Shearer,0.0343,-0.0003,-0.0022,0.0016,-0.0287,-0.007293,-0.016507
2,2,1000017,2005/1/1,"Jennison Small Company Fund, Inc; Class A Shares",-0.017783,John P. Mullman,0.0343,-0.0003,-0.0022,0.0016,-0.0287,-0.019383,-0.028596
3,3,1000030,2005/1/1,"AllianceBernstein Growth & Income Fund, Inc; C...",-0.008071,Frank Caruso,0.0343,-0.0003,-0.0022,0.0016,-0.0287,-0.009671,-0.018885
4,4,1000054,2005/1/1,Fidelity Advisor Series I: Fidelity Advisor Eq...,-0.032812,Jason Weiner,0.0343,-0.0003,-0.0022,0.0016,-0.0287,-0.034412,-0.043626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71318,71318,1052687,2021/12/1,ALPS ETF Trust: ALPS Hillman Active Value ETF,0.045427,Mark A. Hillman,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.045427,0.046139
71319,71319,1052803,2021/12/1,Ultimus Managers Trust: Westwood SmallCap Grow...,0.032446,Adrian Helfert,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.032446,0.033158
71320,71320,1052862,2021/12/1,"Morgan Stanley Institutional Fund, Inc: US Foc...",0.096784,Laurel Durkay,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.096784,0.097496
71321,71321,1052900,2021/12/1,Collaborative Investment Series Trust: Tuttle ...,0.073453,Matthew Tuttle,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.073453,0.074165
71322,71322,1052938,2021/12/1,Vanguard Whitehall Funds: Vanguard Advice Sele...,0.082951,Donald J. Kilbride,-0.0155,-0.0132,-0.0044,0.0000,0.0090,0.082951,0.083663