<a href="https://colab.research.google.com/github/zuozuo11/UMASS/blob/main/Simple_linear_regression_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm # simple linear regression model as there is only one independent variable

In [ ]:
data=pd.read_csv('/content/excess_fund_return.csv')
data

,Unnamed: 0,crsp_portno,m_date,fund_name,weight_mret,mgr_name,mktrf,smb,hml,rf,umd,adjust_date,efr
0,0,1000005,2005/1/1,BlackRock Natural Resources Trust; Investor A ...,0.028175,Robert M. Shearer,0.0343,-0.0003,-0.0022,0.0016,-0.0287,2005/1/1,0.026575
1,1,1000009,2005/1/1,Merrill Lynch Equity Dividend Fund; Class A Sh...,-0.005693,Robert M. Shearer,0.0343,-0.0003,-0.0022,0.0016,-0.0287,2005/1/1,-0.007293
2,2,1000017,2005/1/1,"Jennison Small Company Fund, Inc; Class A Shares",-0.017783,John P. Mullman,0.0343,-0.0003,-0.0022,0.0016,-0.0287,2005/1/1,-0.019383
3,3,1000030,2005/1/1,"AllianceBernstein Growth & Income Fund, Inc; C...",-0.008071,Frank Caruso,0.0343,-0.0003,-0.0022,0.0016,-0.0287,2005/1/1,-0.009671
4,4,1000054,2005/1/1,Fidelity Advisor Series I: Fidelity Advisor Eq...,-0.032812,Jason Weiner,0.0343,-0.0003,-0.0022,0.0016,-0.0287,2005/1/1,-0.034412
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71318,71318,1052687,2021/12/1,ALPS ETF Trust: ALPS Hillman Active Value ETF,0.045427,Mark A. Hillman,-0.0155,-0.0132,-0.0044,0.0000,0.0090,2021/12/1,0.045427
71319,71319,1052803,2021/12/1,Ultimus Managers Trust: Westwood SmallCap Grow...,0.032446,Adrian Helfert,-0.0155,-0.0132,-0.0044,0.0000,0.0090,2021/12/1,0.032446
71320,71320,1052862,2021/12/1,"Morgan Stanley Institutional Fund, Inc: US Foc...",0.096784,Laurel Durkay,-0.0155,-0.0132,-0.0044,0.0000,0.0090,2021/12/1,0.096784
71321,71321,1052900,2021/12/1,Collaborative Investment Series Trust: Tuttle ...,0.073453,Matthew Tuttle,-0.0155,-0.0132,-0.0044,0.0000,0.0090,2021/12/1,0.073453
71322,71322,1052938,2021/12/1,Vanguard Whitehall Funds: Vanguard Advice Sele...,0.082951,Donald J. Kilbride,-0.0155,-0.0132,-0.0044,0.0000,0.0090,2021/12/1,0.082951

In [ ]:
feature_cols = ['mktrf']

In [ ]:
X = data[feature_cols]# Feature
y = data.efr #target variable

In [ ]:
reg = sm.OLS(y, X).fit()

In [ ]:
reg_result = reg.resid

In [ ]:
reg_result

0        0.021010
1       -0.012858
2       -0.024947
3       -0.015236
4       -0.039977
           ...
71318    0.047942
71319    0.034961
71320    0.099299
71321    0.075968
71322    0.085466
Length: 71323, dtype: float64

In [ ]:
reg_result.to_csv(path_or_buf="d.csv")